# name of the source file
filename = "flash.xlsx"

# put the total number of rows and columns of the original document here
# Original document should have no headers or blank rows
sheet.name = "DB_without_header"
sheet.rows = +7151
sheet.cols = "FK"

# Enter the number of cols in the output file
# output.cols = 

# Put all the Mappings here
# Mapping format : 
# mapto.<column identifier in source> = <column identifier in output>
# Multiple columns in source can map to one column in output
# Example: 

mapto.A = "A" #
mapto.E = "I" # implement cases where one source maps to multiple destinations
#mapto.E = "K"
mapto.C = "E"
mapto.DG = "B"
mapto.D = "F"

mapto.AN = "U"
mapto.AO = "V"
mapto.AP = "W"
mapto.AQ = "X"


#AN:AQ ="U:X"

#mapto.start.source ="AN"
#mapto.start.des ="U"
#mapto.end.source ="CY"
#mapto.end.des ="X"

# The separator that is going to be used to separate multiple values
separator = "|"

# Put all the headings of the output excel document here
header.A = "Supplier Status (Mandatory)" #blank
header.B = "UPC/EAN (Mandatory)" # 12 digit identifier
header.C = "Identifier Type (Mandatory)" # UPC / blank?
header.D = "Override GS1 Check?" # blank
header.E = "MPN (Mandatory)" # Manufacturer Part Number
header.F = "Product Name (Original as Per Supplier) (Mandatory)" 
header.G = "Brand (Mandatory)" # (in this case, blank)
header.H = "Product Category" # (in this case, blank)
header.I = "Dropship Gross Purchase Price" # Price
header.J = "Dropship Discount" # blank
header.K = "Dropship Net Purchase Price" # (in this case, blank)
header.L = "Dropship Supplier Shipping Charge SKU Flat Rate" # (in this case, blank)
header.M = "Dropship Supplier Shipping Charge SKU % Rate" # (in this case, blank)
header.N = "Dropship Supplier Handling Charge Rate" # (in this case, blank)
header.O = "Dropship Outbound Shipment Type" # DE - SPD vs LTL (Small Parcel Delivery vs Less Than Truck Load)
header.P = "Fragile" # (in this case, blank)
header.Q = "Override Shipping Method?" # (in this case, blank)
header.R = "Override Dropship Outbound Carrier" # (in this case, blank)
header.S = "Override Dropship Order Handling Time" # (in this case, blank)
header.T = "# of Cartons" #blank
header.U = "Box 1 Shipping Length (in.) (Mandatory)"
header.V = "Box 1 Shipping Breadth (in.) (Mandatory)" 
header.W = "Box 1 Shipping Height (in.) (Mandatory)"
header.X = "Box 1 Shipping Weight (lbs.) (Mandatory)"
header.Y = "Box 2 Shipping Length (in.) (Mandatory)"
header.Z = "Box 2 Shipping Breadth (in.) (Mandatory)" 
header.AA = "Box 2 Shipping Height (in.) (Mandatory)"
header.AB = "Box 2 Shipping Weight (lbs.) (Mandatory)"
header.AC = "Box 3 Shipping Length (in.) (Mandatory)"
header.AD = "Box 3 Shipping Breadth (in.) (Mandatory)" 
header.AE = "Box 3 Shipping Height (in.) (Mandatory)"
header.AF = "Box 3 Shipping Weight (lbs.) (Mandatory)"
header.AG = "Box 4 Shipping Length (in.) (Mandatory)"
header.AH = "Box 4 Shipping Breadth (in.) (Mandatory)" 
header.AI = "Box 4 Shipping Height (in.) (Mandatory)"
header.AJ = "Box 4 Shipping Weight (lbs.) (Mandatory)"
header.AK = "Box 5 Shipping Length (in.) (Mandatory)"
header.AL = "Box 5 Shipping Breadth (in.) (Mandatory)" 
header.AM = "Box 5 Shipping Height (in.) (Mandatory)"
header.AN = "Box 5 Shipping Weight (lbs.) (Mandatory)"
header.AO = "Box 6 Shipping Length (in.) (Mandatory)"
header.AP = "Box 6 Shipping Breadth (in.) (Mandatory)" 
header.AQ = "Box 6 Shipping Height (in.) (Mandatory)"
header.AR = "Box 6 Shipping Weight (lbs.) (Mandatory)"
header.AS = "Box 7 Shipping Length (in.) (Mandatory)"
header.AT = "Box 7 Shipping Breadth (in.) (Mandatory)" 
header.AU = "Box 7 Shipping Height (in.) (Mandatory)"
header.AV = "Box 7 Shipping Weight (lbs.) (Mandatory)"
header.AW = "Box 8 Shipping Length (in.) (Mandatory)"
header.AX = "Box 8 Shipping Breadth (in.) (Mandatory)" 
header.AY = "Box 8 Shipping Height (in.) (Mandatory)"
header.AZ = "Box 8 Shipping Weight (lbs.) (Mandatory)"
header.BA = "Box 9 Shipping Length (in.) (Mandatory)"
header.BB = "Box 9 Shipping Breadth (in.) (Mandatory)" 
header.BC = "Box 9 Shipping Height (in.) (Mandatory)"
header.BD = "Box 9 Shipping Weight (lbs.) (Mandatory)"
header.BE = "Box 10 Shipping Length (in.) (Mandatory)"
header.BF = "Box 10 Shipping Breadth (in.) (Mandatory)" 
header.BG = "Box 10 Shipping Height (in.) (Mandatory)"
header.BH = "Box 10 Shipping Weight (lbs.) (Mandatory)"
header.BI = "Bulk Gross Purchase Price"
header.BJ = "Bulk Discount"
header.BK = "Bulk Net Purchase Price"
header.BL = "Case Pack/Master Carton (Units)"
header.BM = "Case Pack / Master Carton Shipping L (in.)"
header.BN = "Case Pack / Master Carton Shipping B (in.)"
header.BO = "Case Pack / Master Carton Shipping H (in.)"
header.BP = "Case Pack / Master Carton Shipping W (lbs.)"
header.BQ = "Available in Warehouse #1"
header.BR = "Available in Warehouse #2"
header.BS = "Available in Warehouse #3"
header.BT = "MAP"
header.BU = "Harmonized Code"
header.BV = "Listing attributes"
header.BW = "MOQ"
header.BX = "Tariff #"
header.BY = "Freight Class"
header.BZ = "Keywords"
header.CA = "Color/Finish"
header.CB = "Country of Manufacture"
header.CC = "MSRP"
header.CD = "Primary Material"
header.CE = "Distressed Finish? (y/n)"
header.CF = "Assembly Required? (y/n)"
header.CG = "Assembled Item Dimensions (Width)"
header.CH = "Assembled Item Dimensions (Depth)"
header.CI = "Assembled Item Dimensions (Height)"
header.CJ = "Assembled Item Weight"
header.CK = "Item Description"
header.CL = "feature 1"
header.CM = "feature 2"
header.CN = "feature 3"
header.CO = "feature 4"
header.CP = "feature 5"
header.CQ = "feature 6"
header.CR = "feature 7"
header.CS = "feature 8"
header.CT = "feature 9"
header.CU = "Image 1"
header.CV = "Image 2"
header.CW = "Image 3"
header.CX = "Image 4"
header.CY = "Image 5"
header.CZ = "Image 6"
header.DA = "Collection"
header.DB = "Includes" 
