# name of the source file
filename = "source.xlsx"

# put the total number of rows and columns of the original document here
# Original document should have no headers or blank rows
sheet.name = "output_sheet"
sheet.rows = +2
sheet.cols = +2

# Enter the number of cols in the output file
# output.cols = 

# Put all the Mappings here
# Mapping format : 
# <column identifier in source> = <column identifier in output>
# Multiple columns in source can map to one column in output
# Example: 
# B = E
# AG = E
mapto.B = "E"
mapto.A = "E"

# Put all the headings of the output excel document here
# Example: 
header.B = "Title"
header.C = "Price"
header.D = "Tag"
header.E = "MappedValues"

# The separator that is going to be used to separate multiple values
separator = "|"

