
# Details of the source sheet. Edit in case info is wrong 

sheet.name = "sheet"
sheet.headerrow = +2
sheet.datastartrow = +3
sheet.dataendrow = +5985
sheet.skiprows = ""
sheet.cols = "AI"

# Put all the mappings here
# If one column maps to several columns, separate them with a comma
# DO NOT PUT WHITESPACE AFTER COMMA!
# For example: mapsto.A = "B,X"

mapsto.A = "" # Kit or Component
mapsto.B = "" # Item No.
mapsto.C = "" # Description 
mapsto.D = "" # Color/Finish 
mapsto.E = "" # Collection  Name
mapsto.F = "" # Case Qty
mapsto.G = "" # Pc / Set
mapsto.H = "" # # of Carton
mapsto.I = "" # Dropship Price (Freight not Included)
mapsto.J = "" # UPC
mapsto.K = "" # Overall Size :  
mapsto.L = "" # Size Notes: 

# beginning of the box mappings. Please do not change these.
mapsto.M = "U" 
mapsto.N = "V" 
mapsto.O = "W" 
mapsto.P = "X" 
# end of the box mappings.

mapsto.Q = "" # Seat  Length (inch)
mapsto.R = "" # Seat  Depth (inch)
mapsto.S = "" # Seat Height (inch)
mapsto.T = "" # Carton Length (inch)
mapsto.U = "" # Carton Width (inch)
mapsto.V = "" # Carton Height  (inch)
mapsto.W = "" # Carton Weight (lb)
mapsto.X = "" # Ship Type:
mapsto.Y = "" # Country
mapsto.Z = "" # Materials 
mapsto.AA = "" # Upholstery Finish
mapsto.AB = "" # Assembly  Required?
mapsto.AC = "" # Style
mapsto.AD = "" # Romance
mapsto.AE = "" # Features  Catalog
mapsto.AF = "" # Details: Construction, What is Included?  
mapsto.AG = "" # Weight Capacity: RESIDENTIAL USE ONLY

# These are the headers for the output file. Please do not change these.
header.A = "Supplier Status (Mandatory)"
header.B = "UPC/EAN (Mandatory)"
header.C = "Identifier Type (Mandatory)" 
header.D = "Override GS1 Check?" 
header.E = "MPN (Mandatory)" 
header.F = "Product Name (Original as Per Supplier) (Mandatory)"
header.G = "Brand (Mandatory)" 
header.H = "Product Category" 
header.I = "Dropship Gross Purchase Price" 
header.J = "Dropship Discount" 
header.K = "Dropship Net Purchase Price"
header.L = "Dropship Supplier Shipping Charge SKU Flat Rate"
header.M = "Dropship Supplier Shipping Charge SKU % Rate"
header.N = "Dropship Supplier Handling Charge Rate"
header.O = "Dropship Outbound Shipment Type"
header.P = "Fragile"
header.Q = "Override Shipping Method?"
header.R = "Override Dropship Outbound Carrier"
header.S = "Override Dropship Order Handling Time"
header.T = "# of Cartons"
header.U = "Box 1 Shipping Length (in.) (Mandatory)"
header.V = "Box 1 Shipping Breadth (in.) (Mandatory)"
header.W = "Box 1 Shipping Height (in.) (Mandatory)"
header.X = "Box 1 Shipping Weight (lbs.) (Mandatory)"
header.Y = "Bulk Gross Purchase Price"
header.Z = "Bulk Discount"
header.AA = "Bulk Net Purchase Price"
header.AB = "Case Pack/Master Carton (Units)"
header.AC = "Case Pack / Master Carton Shipping L (in.)"
header.AD = "Case Pack / Master Carton Shipping B (in.)"
header.AE = "Case Pack / Master Carton Shipping H (in.)"
header.AF = "Case Pack / Master Carton Shipping W (lbs.)"
header.AG = "Available in Warehouse #1"
header.AH = "Available in Warehouse #2"
header.AI = "Available in Warehouse #3"
header.AJ = "MAP"
header.AK = "Harmonized Code"
header.AL = "Listing attributes"
header.AM = "MOQ"
header.AN = "Tariff #"
header.AO = "Freight Class"
header.AP = "Keywords"
header.AQ = "Color/Finish"
header.AR = "Country of Manufacture"
header.AS = "MSRP"
header.AT = "Primary Material"
header.AU = "Distressed Finish? (y/n)"
header.AV = "Assembly Required? (y/n)"
header.AW = "Assembled Item Dimensions (Width)"
header.AX = "Assembled Item Dimensions (Depth)"
header.AY = "Assembled Item Dimensions (Height)"
header.AZ = "Assembled Item Weight"
header.BA = "Item Description"
header.BB = "feature 1"
header.BC = "feature 2"
header.BD = "feature 3"
header.BE = "feature 4"
header.BF = "feature 5"
header.BG = "feature 6"
header.BH = "feature 7"
header.BI = "feature 8"
header.BJ = "feature 9"
header.BK = "Image 1"
header.BL = "Image 2"
header.BM = "Image 3"
header.BN = "Image 4"
header.BO = "Image 5"
header.BP = "Image 6"
header.BQ = "Collection"
header.BR = "Includes"
