# Details of the source sheet. Edit in case info is wrong 

sheet.name = "DB"
sheet.rows = +7151
sheet.cols = "FP"

# Put all the mappings here
# If one column maps to several columns, separate them with a comma
# DO NOT PUT WHITESPACE AFTER COMMA!
# For example: mapsto.A = "B,X"

mapsto.A = "A" # Status
mapsto.B = "" # Short Description
mapsto.C = "E" # Product Code Computed
mapsto.D = "DI" # Product Description
mapsto.E = "I,K" # Flash FOB Price
mapsto.F = "" # Flash Internet Only Landed Cost
mapsto.G = "" # NMFC Code (Text)
mapsto.H = "" # Capacity
mapsto.I = "F" # Product Series
mapsto.J = "DA" # MSRP List Price
mapsto.K = "" # Flash Product Description
mapsto.L = "" # Caption 1
mapsto.M = "" # Caption 2
mapsto.N = "" # Caption 3
mapsto.O = "" # Caption 4
mapsto.P = "" # Caption 5
mapsto.Q = "" # Caption 6
mapsto.R = "" # Caption 7
mapsto.S = "" # Caption 8
mapsto.T = "" # Caption 9
mapsto.U = "" # Caption 10
mapsto.V = "" # Caption 11
mapsto.W = "" # Caption 12
mapsto.X = "" # Caption 13
mapsto.Y = "" # Caption 14
mapsto.Z = "" # Caption 15
mapsto.AA = "" # Caption 16
mapsto.AB = "" # Caption 17
mapsto.AC = "" # Caption 18
mapsto.AD = "" # Caption 19
mapsto.AE = "" # Caption 20
mapsto.AF = "DS" # Image 1
mapsto.AG = "DT" # Image 2
mapsto.AH = "DU" # Image 3
mapsto.AI = "DV" # Image 4
mapsto.AJ = "DW" # Image 5
mapsto.AK = "CO" # Availability
mapsto.AL = "" # Overall Dimension
mapsto.AM = "" # Single Unit Weight

# beginning of the box mappings. Please do not change these.
mapsto.AN = "U" 
mapsto.AO = "V" 
mapsto.AP = "W" 
mapsto.AQ = "X" 
mapsto.AR = "Y" 
mapsto.AS = "Z" 
mapsto.AT = "AA" 
mapsto.AU = "AB" 
mapsto.AV = "AC" 
mapsto.AW = "AD" 
mapsto.AX = "AE" 
mapsto.AY = "AF" 
mapsto.AZ = "AG" 
mapsto.BA = "AH" 
mapsto.BB = "AI" 
mapsto.BC = "AJ" 
mapsto.BD = "AK" 
mapsto.BE = "AL" 
mapsto.BF = "AM" 
mapsto.BG = "AN" 
mapsto.BH = "AO" 
mapsto.BI = "AP" 
mapsto.BJ = "AQ" 
mapsto.BK = "AR" 
mapsto.BL = "AS" 
mapsto.BM = "AT" 
mapsto.BN = "AU" 
mapsto.BO = "AV" 
mapsto.BP = "AW" 
mapsto.BQ = "AX" 
mapsto.BR = "AY" 
mapsto.BS = "AZ" 
mapsto.BT = "BA" 
mapsto.BU = "BB" 
mapsto.BV = "BC" 
mapsto.BW = "BD" 
mapsto.BX = "BE" 
mapsto.BY = "BF" 
mapsto.BZ = "BG" 
mapsto.CA = "BH" 
mapsto.CB = "BI" 
mapsto.CC = "BJ" 
mapsto.CD = "BK" 
mapsto.CE = "BL" 
mapsto.CF = "BM" 
mapsto.CG = "BN" 
mapsto.CH = "BO" 
mapsto.CI = "BP" 
mapsto.CJ = "BQ" 
mapsto.CK = "BR" 
mapsto.CL = "BS" 
mapsto.CM = "BT" 
mapsto.CN = "BU" 
mapsto.CO = "BV" 
mapsto.CP = "BW" 
mapsto.CQ = "BX" 
mapsto.CR = "BY" 
mapsto.CS = "BZ" 
mapsto.CT = "CA" 
mapsto.CU = "CB" 
mapsto.CV = "CC" 
mapsto.CW = "CD" 
mapsto.CX = "CE" 
mapsto.CY = "CF" 
mapsto.CZ = "CG" 
mapsto.DA = "CH" 
mapsto.DB = "CI" 
mapsto.DC = "CJ" 
# end of the box mappings.

mapsto.DD = "" # Seat Height
mapsto.DE = "" # LTL Only
mapsto.DF = "" # Number of Parcels
mapsto.DG = "B" # UPC Code
mapsto.DH = "DD" # Assembly Required
mapsto.DI = "CY" # Color
mapsto.DJ = "" # Data Mapping Color
mapsto.DK = "" # Finish
mapsto.DL = "" # Upholstery
mapsto.DM = "DB" # Material
mapsto.DN = "CX" # Keywords
mapsto.DO = "" # Flash Path
mapsto.DP = "C" # Product Type
mapsto.DQ = "CZ" # Made In
mapsto.DR = "" # Main Category
mapsto.DS = "" # Category
mapsto.DT = "" # Data Mapping Category
mapsto.DU = "" # youtube video link
mapsto.DV = "L" # Parent SKU
mapsto.DW = "" # Freight Class
mapsto.DX = "" # Eligible for $850+ Free Ship Program
mapsto.DY = "" # Warranty
mapsto.DZ = "" # Item Weight
mapsto.EA = "" # Minimum Qty Required
mapsto.EB = "" # Back Material
mapsto.EC = "" # Frame Material
mapsto.ED = "" # Seat Material
mapsto.EE = "" # Table Top Material
mapsto.EF = "" # Adjustable
mapsto.EG = "" # Adjustable Arms
mapsto.EH = "" # Arms
mapsto.EI = "" # Big and Tall
mapsto.EJ = "" # CAL 117 Certified
mapsto.EK = "" # CARB 2 Wood
mapsto.EL = "" # Distressed Finish
mapsto.EM = "" # Folding
mapsto.EN = "" # Lid included
mapsto.EO = "" # Massaging
mapsto.EP = "" # Mobile
mapsto.EQ = "" # Motorized
mapsto.ER = "" # Nesting
mapsto.ES = "" # Number of Shelves
mapsto.ET = "" # Quantity in Set
mapsto.EU = "" # Rated For Commercial Use
mapsto.EV = "" # Reclining
mapsto.EW = "" # Reversible
mapsto.EX = "" # Under Seat Storage
mapsto.EY = "" # Seat Thickness
mapsto.EZ = "" # Seating Capacity
mapsto.FA = "" # Degree of Swivel
mapsto.FB = "" # Stack Quantity
mapsto.FC = "" # Ottoman Depth
mapsto.FD = "" # Ottoman Height
mapsto.FE = "" # Ottoman Width
mapsto.FF = "" # Diameter Min
mapsto.FG = "" # Back Color
mapsto.FH = "" # Frame Color
mapsto.FI = "" # Seat Color
mapsto.FJ = "" # Table Top Color
mapsto.FK = "" # Style
mapsto.FL = "" # Layout
mapsto.FM = "" # Back Type
mapsto.FN = "" # Back Style
mapsto.FO = "" # Base Style
mapsto.FP = "" # Table Shape

# These are the headers for the output file. Please do not change these.
header.A = "Supplier Status (Mandatory)"
header.B = "UPC/EAN (Mandatory)"
header.C = "Identifier Type (Mandatory)" 
header.D = "Override GS1 Check?" 
header.E = "MPN (Mandatory)" 
header.F = "Product Name (Original as Per Supplier) (Mandatory)"
header.G = "Brand (Mandatory)" 
header.H = "Product Category" 
header.I = "Dropship Gross Purchase Price" 
header.J = "Dropship Discount" 
header.K = "Dropship Net Purchase Price"
header.L = "Dropship Supplier Shipping Charge SKU Flat Rate"
header.M = "Dropship Supplier Shipping Charge SKU % Rate"
header.N = "Dropship Supplier Handling Charge Rate"
header.O = "Dropship Outbound Shipment Type"
header.P = "Fragile"
header.Q = "Override Shipping Method?"
header.R = "Override Dropship Outbound Carrier"
header.S = "Override Dropship Order Handling Time"
header.T = "# of Cartons"
header.U = "Box 1 Shipping Length (in.) (Mandatory)"
header.V = "Box 1 Shipping Breadth (in.) (Mandatory)"
header.W = "Box 1 Shipping Height (in.) (Mandatory)"
header.X = "Box 1 Shipping Weight (lbs.) (Mandatory)"
header.Y = "Box 2 Shipping Length (in.) (Mandatory)"
header.Z = "Box 2 Shipping Breadth (in.) (Mandatory)"
header.AA = "Box 2 Shipping Height (in.) (Mandatory)"
header.AB = "Box 2 Shipping Weight (lbs.) (Mandatory)"
header.AC = "Box 3 Shipping Length (in.) (Mandatory)"
header.AD = "Box 3 Shipping Breadth (in.) (Mandatory)"
header.AE = "Box 3 Shipping Height (in.) (Mandatory)"
header.AF = "Box 3 Shipping Weight (lbs.) (Mandatory)"
header.AG = "Box 4 Shipping Length (in.) (Mandatory)"
header.AH = "Box 4 Shipping Breadth (in.) (Mandatory)"
header.AI = "Box 4 Shipping Height (in.) (Mandatory)"
header.AJ = "Box 4 Shipping Weight (lbs.) (Mandatory)"
header.AK = "Box 5 Shipping Length (in.) (Mandatory)"
header.AL = "Box 5 Shipping Breadth (in.) (Mandatory)"
header.AM = "Box 5 Shipping Height (in.) (Mandatory)"
header.AN = "Box 5 Shipping Weight (lbs.) (Mandatory)"
header.AO = "Box 6 Shipping Length (in.) (Mandatory)"
header.AP = "Box 6 Shipping Breadth (in.) (Mandatory)"
header.AQ = "Box 6 Shipping Height (in.) (Mandatory)"
header.AR = "Box 6 Shipping Weight (lbs.) (Mandatory)"
header.AS = "Box 7 Shipping Length (in.) (Mandatory)"
header.AT = "Box 7 Shipping Breadth (in.) (Mandatory)"
header.AU = "Box 7 Shipping Height (in.) (Mandatory)"
header.AV = "Box 7 Shipping Weight (lbs.) (Mandatory)"
header.AW = "Box 8 Shipping Length (in.) (Mandatory)"
header.AX = "Box 8 Shipping Breadth (in.) (Mandatory)"
header.AY = "Box 8 Shipping Height (in.) (Mandatory)"
header.AZ = "Box 8 Shipping Weight (lbs.) (Mandatory)"
header.BA = "Box 9 Shipping Length (in.) (Mandatory)"
header.BB = "Box 9 Shipping Breadth (in.) (Mandatory)"
header.BC = "Box 9 Shipping Height (in.) (Mandatory)"
header.BD = "Box 9 Shipping Weight (lbs.) (Mandatory)"
header.BE = "Box 10 Shipping Length (in.) (Mandatory)"
header.BF = "Box 10 Shipping Breadth (in.) (Mandatory)"
header.BG = "Box 10 Shipping Height (in.) (Mandatory)"
header.BH = "Box 10 Shipping Weight (lbs.) (Mandatory)"
header.BI = "Box 11 Shipping Length (in.) (Mandatory)"
header.BJ = "Box 11 Shipping Breadth (in.) (Mandatory)"
header.BK = "Box 11 Shipping Height (in.) (Mandatory)"
header.BL = "Box 11 Shipping Weight (lbs.) (Mandatory)"
header.BM = "Box 12 Shipping Length (in.) (Mandatory)"
header.BN = "Box 12 Shipping Breadth (in.) (Mandatory)"
header.BO = "Box 12 Shipping Height (in.) (Mandatory)"
header.BP = "Box 12 Shipping Weight (lbs.) (Mandatory)"
header.BQ = "Box 13 Shipping Length (in.) (Mandatory)"
header.BR = "Box 13 Shipping Breadth (in.) (Mandatory)"
header.BS = "Box 13 Shipping Height (in.) (Mandatory)"
header.BT = "Box 13 Shipping Weight (lbs.) (Mandatory)"
header.BU = "Box 14 Shipping Length (in.) (Mandatory)"
header.BV = "Box 14 Shipping Breadth (in.) (Mandatory)"
header.BW = "Box 14 Shipping Height (in.) (Mandatory)"
header.BX = "Box 14 Shipping Weight (lbs.) (Mandatory)"
header.BY = "Box 15 Shipping Length (in.) (Mandatory)"
header.BZ = "Box 15 Shipping Breadth (in.) (Mandatory)"
header.CA = "Box 15 Shipping Height (in.) (Mandatory)"
header.CB = "Box 15 Shipping Weight (lbs.) (Mandatory)"
header.CC = "Box 16 Shipping Length (in.) (Mandatory)"
header.CD = "Box 16 Shipping Breadth (in.) (Mandatory)"
header.CE = "Box 16 Shipping Height (in.) (Mandatory)"
header.CF = "Box 16 Shipping Weight (lbs.) (Mandatory)"
header.CG = "Bulk Gross Purchase Price"
header.CH = "Bulk Discount"
header.CI = "Bulk Net Purchase Price"
header.CJ = "Case Pack/Master Carton (Units)"
header.CK = "Case Pack / Master Carton Shipping L (in.)"
header.CL = "Case Pack / Master Carton Shipping B (in.)"
header.CM = "Case Pack / Master Carton Shipping H (in.)"
header.CN = "Case Pack / Master Carton Shipping W (lbs.)"
header.CO = "Available in Warehouse #1"
header.CP = "Available in Warehouse #2"
header.CQ = "Available in Warehouse #3"
header.CR = "MAP"
header.CS = "Harmonized Code"
header.CT = "Listing attributes"
header.CU = "MOQ"
header.CV = "Tariff #"
header.CW = "Freight Class"
header.CX = "Keywords"
header.CY = "Color/Finish"
header.CZ = "Country of Manufacture"
header.DA = "MSRP"
header.DB = "Primary Material"
header.DC = "Distressed Finish? (y/n)"
header.DD = "Assembly Required? (y/n)"
header.DE = "Assembled Item Dimensions (Width)"
header.DF = "Assembled Item Dimensions (Depth)"
header.DG = "Assembled Item Dimensions (Height)"
header.DH = "Assembled Item Weight"
header.DI = "Item Description"
header.DJ = "feature 1"
header.DK = "feature 2"
header.DL = "feature 3"
header.DM = "feature 4"
header.DN = "feature 5"
header.DO = "feature 6"
header.DP = "feature 7"
header.DQ = "feature 8"
header.DR = "feature 9"
header.DS = "Image 1"
header.DT = "Image 2"
header.DU = "Image 3"
header.DV = "Image 4"
header.DW = "Image 5"
header.DX = "Image 6"
header.DY = "Collection"
header.DZ = "Includes"
